# Changes here will be overwritten by Copier
_commit: 0.0.29
_src_path: gh:edgarrmondragon/singer-tap-copier-template
author_email: edgarrm358@gmail.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
dependabot_update_time: '10:00'
dependabot_update_timezone: UTC
python_main_version: '3.11'
repository_name: tap-socketdev
repository_namespace: edgarrmondragon
repository_provider: github.com
repository_visibility: public
tap_auth_method: API Key
tap_id: tap-socketdev
tap_package_command_line_name: tap-socketdev
tap_package_distribution_name: tap-socketdev
tap_package_import_name: tap_socketdev
tap_source_description: Supply chain security
tap_source_id: SocketDev
tap_source_name: Socket
tap_stream_type: REST
vscode_files: true
